#From openjdk:8
#copy ./target/SAIAFarming-0.0.1-SNAPSHOT.jar SAIAFarming-0.0.1-SNAPSHOT.jar
copy SAIAFarming-0.0.1-SNAPSHOT.jar SAIAFarming-0.0.1-SNAPSHOT.jar
CMD ["java","-Dspring.config.location=/opt/applicationorg.properties","-jar","SAIAFarming-0.0.1-SNAPSHOT.jar"]
